#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RESET_DB=false
for arg in "$@"; do
  case "$arg" in
    --reset)
      RESET_DB=true
      ;;
    --help|-h)
      cat <<'HELP'
Usage:
  bash scripts/dev-local.sh          Start Supabase, export local env, build, and run API
  bash scripts/dev-local.sh --reset  Also reset local DB and apply migrations first

Run this from WSL. Docker Desktop must be running with WSL integration enabled.
This script never overwrites an existing .env file.
HELP
      exit 0
      ;;
    *)
      echo "Unknown option: $arg"
      exit 1
      ;;
  esac
done

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1"
    exit 1
  fi
}

extract_status_value() {
  local label="$1"
  printf '%s\n' "$STATUS" | sed 's/│/|/g' | awk -F'|' -v label="$label" '
    {
      for (i=1; i<=NF; i++) {
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", $i)
        if ($i == label) {
          val=$(i+1)
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
          print val
          exit
        }
      }
    }
  '
}

need_command npm
need_command npx
need_command docker

if ! docker info >/dev/null 2>&1; then
  echo "Docker is not reachable from WSL."
  echo "Start Docker Desktop, then enable: Settings -> Resources -> WSL integration."
  exit 1
fi

if [ ! -d node_modules ]; then
  echo "Installing dependencies..."
  npm install
fi

if [ ! -f .env ]; then
  echo "Creating .env from env.example..."
  cp env.example .env
else
  echo "Keeping existing .env unchanged."
fi

echo "Starting local Supabase..."
npx supabase start >/dev/null

STATUS="$(npx supabase status)"
API_URL="$(extract_status_value "Project URL")"
DB_URL="$(extract_status_value "URL")"
STUDIO_URL="$(extract_status_value "Studio")"
SERVICE_ROLE_KEY="$(extract_status_value "Secret")"

if [ -z "$API_URL" ] || [ -z "$SERVICE_ROLE_KEY" ]; then
  echo "Could not read local Supabase URL/key from 'npx supabase status'."
  echo "$STATUS"
  exit 1
fi

export NODE_ENV="${NODE_ENV:-development}"
export PORT="${PORT:-8081}"
export FRONTEND_URL="${FRONTEND_URL:-http://localhost:8081}"
export SUPABASE_URL="$API_URL"
export SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY"

if [ -z "${JWT_SECRET:-}" ]; then
  if grep -q '^JWT_SECRET=' .env 2>/dev/null; then
    JWT_SECRET="$(grep '^JWT_SECRET=' .env | tail -n 1 | cut -d '=' -f 2-)"
    export JWT_SECRET
  elif command -v openssl >/dev/null 2>&1; then
    export JWT_SECRET="$(openssl rand -hex 32)"
  else
    export JWT_SECRET="$(date +%s%N | sha256sum | awk '{print $1}')"
  fi
fi

cat > .env.local.generated <<EOF
# Generated by scripts/dev-local.sh for reference only.
# The script exports these values for its current process.
# Your existing .env is not modified.
NODE_ENV=$NODE_ENV
PORT=$PORT
FRONTEND_URL=$FRONTEND_URL
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
EOF

if [ "$RESET_DB" = true ]; then
  echo "Resetting local database and applying migrations..."
  npx supabase db reset
fi

echo "Building backend..."
npm run build

cat <<INFO

Local backend configuration is ready.

API server:    http://localhost:8081
Supabase API:  $API_URL
Supabase DB:   $DB_URL
Studio:        $STUDIO_URL

Your .env file was not modified.
Reference local values were written to .env.local.generated.

Open Studio directly in your Windows browser. If Chrome shows a chrome-error:// page,
open a new tab and paste the Studio URL manually instead of reloading the error page.

Starting backend...
INFO

npm run dev
