"""test migration

Revision ID: 137960895260
Revises: 
Create Date: 2023-03-21 23:07:04.305948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137960895260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
