#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Issue #85: stop the Workers Builds check from failing every PR"

# ── Stage 1: confirm the Worker is actually dead weight ───────────────────
stage "Confirm the littletown Worker has nothing to build"
say "Evidence gathered from this repo before writing this wizard:"
note "- No wrangler.toml / wrangler.jsonc anywhere in the repo, current tree or history."
note "- Frontend deploys via Cloudflare Pages (project 'little-town'), which passes on every commit."
note "- Backend deploys to Render (render.yaml at repo root)."
note "- The failing check is 'Workers Builds: littletown', a separate Cloudflare Worker"
note "  service named 'littletown', wired to this repo via the Cloudflare Workers and Pages"
note "  GitHub App. Nothing in this repo produces a Worker script for it to build."
say ""
say "This points to a leftover: a Worker project set up during an earlier experiment (or as"
say "a first attempt before Pages was chosen) that's still connected to this repo's GitHub"
say "integration, so every push/PR triggers a build with no source to build."
say ""
open_url "https://dash.cloudflare.com/9095b6db39d8f3862a149bf091277a0c/workers/services/view/littletown/production"
step "On the littletown Worker's overview page, check whether it's actually serving traffic"
step "anywhere (custom domains, routes, or a workers.dev URL with real recent requests)."
if confirm "Is the littletown Worker serving real traffic outside this repo (i.e. genuinely in use)?"; then
  warn "Stop here and re-scope: if it's in use, this repo may need a real wrangler config"
  warn "instead of removal. That's a different fix than this wizard covers — come back to"
  warn "issue #85 with what you found instead of disconnecting anything below."
  exit 0
fi
note "Confirmed unused (or unused by anything this repo would build). Continuing to disconnect it."

# ── Stage 2: disconnect the GitHub build integration ──────────────────────
stage "Disconnect the Git build integration from this repo"
say "This stops the check from being posted on PRs without deleting the Worker outright,"
say "in case it's referenced by name somewhere you haven't found yet."
open_url "https://dash.cloudflare.com/9095b6db39d8f3862a149bf091277a0c/workers/services/view/littletown/production/settings"
step "Find the 'Build' section (Cloudflare has moved this between a 'Settings' tab and a"
step "dedicated 'Builds' tab more than once, so look for whichever one exists for you)."
step "Look for 'Git repository' or 'Source' showing alcash55/Little-Town."
step "Click 'Disconnect' (or 'Manage repository access' → remove this repo) to stop future"
step "builds from being triggered on push/PR."
note "Cloudflare docs for this flow, if the UI has moved again:"
note "https://developers.cloudflare.com/workers/ci-cd/builds/git-integration/"
if confirm "Disconnected the Git integration from the littletown Worker?"; then
  note "Good. Once disconnected, Cloudflare stops posting 'Workers Builds: littletown' checks."
else
  SKIPPED+=("Disconnect littletown Worker's Git build integration in the Cloudflare dashboard")
  warn "Left connected. The check keeps failing on every PR until this is done."
fi

if confirm "Also delete the littletown Worker entirely, since it's unused? (skip if unsure)"; then
  open_url "https://dash.cloudflare.com/9095b6db39d8f3862a149bf091277a0c/workers/services/view/littletown/production/settings"
  step "Scroll to 'Delete' at the bottom of Settings and confirm the Worker's name to delete it."
  if confirm "Deleted the littletown Worker?"; then
    note "Worker removed."
  else
    SKIPPED+=("Delete the unused littletown Worker (optional cleanup, not required for #85)")
  fi
else
  note "Left the Worker in place, just disconnected from this repo. Fine either way for #85."
fi

# ── Stage 3: verify the check stops appearing ──────────────────────────────
stage "Verify on a real PR"
say "Acceptance criteria for #85 requires a documentation-only PR to show no failing checks."
step "Open (or push an empty commit to) any open PR against this repo, e.g. one of the"
step "Dependabot PRs already open, or this sprint's own doc PR."
open_url "https://github.com/alcash55/Little-Town/pulls"
step "Confirm the PR's checks no longer include 'Workers Builds: littletown' at all"
step "(not passing, just gone, since the integration no longer watches this repo)."
if confirm "Confirmed the check no longer appears on a fresh PR?"; then
  note "#85 acceptance criteria met: no failing check on a docs-only PR."
else
  SKIPPED+=("Re-check a PR's checks list after disconnecting, to confirm Workers Builds is gone")
fi

finish
